### ISSUE TITLE
PDF support?

### ISSUE THREAD

**Issue by brettburwell** [spacecatninja/craft-imager-x-imageboss-transformer#1]
Hi there! I may be missing something, but it looks like PDFs aren't currently supported. 

Here's the error I'm seeing:
`calculateTargetSize(): Argument #2 ($sourceWidth) must be of type int, null given`

At a glance, I suspect it's because `$source->getWidth()` in line 78 of `ImageBossTransformedImageModel.php` is returning null because Craft can't provide the width of a PDF. 

I'm wondering if a simple fallback value here would help workaround the issue.

**Comment by aelvan** [comment]
This should be fixed now for both the Craft 4 and Craft 5 versions.

Please note that the code you hit only occurs when both dimensions of a transform can't be determined by the transform parameters. Ie, if you'd passed in `{ width: 1200, ratio: 3/4 }` or similar, the width and height can be determined without inspecting the source asset, and you'd not get an error. With the fix in place, you'll no longer get an error, but Imager will still not be able to determine the exact size of the transform, and will calculate the second axis based on a 1:1 ratio. Ie, if you pass in `{ width: 600 }`, both width and height of the transform will be `600`. So, when possible, it would be better to pass in both width and height (or ratio), and if you don't, make sure you don't count on the width and height of the transform to be correct.

**Comment by brettburwell** [comment]
Beautiful. Thanks so much for the quick fix @aelvan. 

And makes sense about the issue only occurring in the limited situation you described (and the benefit of defining a ratio whenever possible). Cheers!
